### PR TITLE
JA: Add community/contribute/docs.md

### PR DESCRIPTION
**Pull request by agrexgh**

### CODE REVIEW

**Comment by agrexgh** [comment]
@googlebot I signed it!

**Comment by AseiSugiyama** [comment]
Hi @agrexgh ! Japanese community is acting at Slack channel #docs-translation of the workspace tfug.slack.com. You can access it from https://tfug.jp/

Could you join our slack channel too?

**Comment by agrexgh** [comment]
> Hi @agrexgh ! Japanese community is acting at Slack channel #docs-translation of the workspace tfug.slack.com. You can access it from https://tfug.jp/
> 
> Could you join our slack channel too?
@AseiSugiyama I have just joined it!

**Comment by AseiSugiyama** [comment]
I think `community/contribution/docs` is a contribution guideline for the global communities and it is better to untranslated. It contains both ways to contribute to English document `site/en` and community translations.

Japanese community has also the contribution guideline. You can check it from https://github.com/tensorflow/docs-l10n/blob/master/site/ja/CONTRIBUTING.md

**Comment by agrexgh** [comment]
@AseiSugiyama 
Thank you for advice! And excuse me for my unknowledge.
But I'd like to translate community/*.
Can I do it and output another document(for example, CONTRIBUTING.md)?

I thought Japanese contributors like me needed Japanese guideline at first,
so it's better for me to translate guideline for contribution at first...

[CONTRIBUTING.md](https://github.com/tensorflow/docs-l10n/blob/master/site/ja/CONTRIBUTING.md) doesn't cover all content of community/contribute/*,
so many Japanese contributors may feel that contributing is difficult for them because of English barrier.

**Comment by agrexgh** [comment]
All reviewers.
Please review these changes.

Warm regards.

**Comment by agrexgh** [comment]
Because of #252,
this PR is inappropriate.
So I close this.
Thank you for your comment, @AseiSugiyama !

**Pull request closed without merging**
