### PR TITLE
Added Name as a contributer

### PR DESCRIPTION
**Pull request by Elamraoui-Sohayb**

### CODE REVIEW

**Comment by lamberta** [comment]
Hello, thanks for signing up as a reviewer!

Running into some CLA bot issues ...
I verified you signed the CLA with your email, but since the commit is not using that same email, address the bot is getting confused.

Would you be able to create another pull request using the email you signed the CLA with? That should fix things for future contributions.

Thanks

**Comment by Elamraoui-Sohayb** [comment]
@lamberta  Thank you for the quick response.
I'm using the same email for both github and CLA account, so i'm little bit confused.
Would trying with a new request and CLA help?

Thanks

**Comment by lamberta** [comment]
It's difficult to see in GitHub's UI, but in the commit history the author email is set to `<32344494+Elamraoui-Sohayb@users.noreply.github.com>` (not your CLA email).
I believe this can be configured within the GitHub settings. If editing locally, you can configure your email/name in the `.gitconfig` file.

**Comment by Elamraoui-Sohayb** [comment]
@lamberta I understand.
That's because i had the email display set to private on my Github account.
It's updated to public now, I think it should work.

Thank you

**Pull request closed without merging**
