### PR TITLE
KO: Translation of tutorials/generative/cvae.ipynb

### PR DESCRIPTION
**Pull request by jaketae**
Uploaded translation of tutorials/generative/cvae.ipynb

### CODE REVIEW

**Comment by jaketae** [comment]
Confirmed that the notebook runs on Google Colab without any errors.

**Comment by rickiepark** [comment]
Thank you @jaketae 
There are many PRs to review. :(
Please wait for a while, I'll back this pr asap. :)

**Comment by jaketae** [comment]
@rickiepark Thank you for the prompt reply, I appreciate it. Please take your time.

**Comment by rickiepark** [comment]
Thank you @jaketae 
But cvae en version seems to update again. :( 
https://www.tensorflow.org/tutorials/generative/cvae

**Comment by lamberta** [comment]
Thanks @jaketae ,
As mentioned on the [mailing list](https://groups.google.com/a/tensorflow.org/g/docs/c/G23C6ZxjiUI/m/z8G87HTfBQAJ), we're directing the community to work alongside vendors in our GitLocalize project. It's the only way to make sure the translations are in sync with the updated source material.

This doc is mostly translated: https://gitlocalize.com/repo/4592/ko/site/en-snapshot/tutorials/generative/cvae.ipynb
Would you be able to look through it and provide a review?

Thanks, will close this PR since the updated version looks close.

**Pull request closed without merging**
