### PR TITLE
[IT] translation for tutorials/customization/custom_layers.ipynb

### PR DESCRIPTION
**Pull request by mcaci**
Italian translation for tutorials/customization/custom_layers.ipynb

### CODE REVIEW

**Comment by mcaci** [comment]
Hello, I returned to translating the documentation since a while now and if I understand correctly I should go via the gitlocalize app. I have to check the procedure or in any case how to do it, I can delete this PR if I need to change the procedure. Cheers, Michele

**Comment by lamberta** [comment]
Thank you, @mcaci !
You can continue to submit notebook pull requests, if you prefer. GitLocalize provides a UI that makes it easier to sync sections. But, as always, getting the community review is always the toughest part :) Open to suggestions for that.

from [site/it/REVIEWERS](https://github.com/tensorflow/docs-l10n/blob/master/site/it/REVIEWERS), cc:  @bhack @codeadmin-peritiae @omonimus1 @maryggiannella @gmb-ftcont
Please take a look. In the interest of review velocity, let's make the standard: "accurate translation and not harmful" (no spam, etc.). Thank you

**Comment by mcaci** [comment]
Alright @lamberta, thank you for the info. It's not always easy to get back to translations with all the right information after a long absence :) Waiting for the reviews then

**Comment by bhack** [comment]
@lamberta Is there a new button/facility to quickly open side by side review? It will really speed-up sparse time reviews.

**Comment by lamberta** [comment]
>  Is there a new button/facility to quickly open side by side review? It will really speed-up sparse time reviews.

@bhack The GitLocalize project has this, at least for sync/submissions: https://gitlocalize.com/tensorflow/docs-l10n

**Comment by lamberta** [comment]
HI @mcaci and @bhack 

I think it's time to move `site/it/` to a community fork since there's not enough support here. Is someone willing to maintain this? We can link to it from our README:

> Language support is determined by a number of factors including—but not limited to—site metrics and demand, community support, English proficiency, audience preference, and other indicators. Since each supported language incurs a cost, unmaintained languages are removed. Support for new languages will be announced on the TensorFlow blog or Twitter.
> 
> If your preferred language is not supported, you are welcome to maintain a community fork for open source contributors. These are not published to tensorflow.org.

Thanks

**Comment by bhack** [comment]
Is this about reviews of lack of PR traffic?

**Comment by lamberta** [comment]
> Is this about reviews or lack of PR traffic?

Both :)

The community translations project started organically and extended us before we could agree on a process to expand coverage and gather support and resources. Now that we have a process to request resources, we need to consolidate and grow more deliberately. The Italian translation community just isn't big enough to provide site coverage (2% [according to GitLocalize](https://gitlocalize.com/tensorflow/docs-l10n)). If I could review the Italian then it would be an easy merge, but right now I'm the bottleneck.

tensorflow.org is a very big and you and @mcaci have done awesome work. But at the size we're at (about 500 guides/tutorials at last count), there's really no way to provide complete coverage without vendor support. I think the community strength is more in translating technical terms and providing feedback, so, in the future, I'd like to make it easier for the community to contribute to the glossary.

Nonetheless, I think these notebooks are useful and would be happy to link to them in a community forks section.

**Comment by bhack** [comment]
Personally I can only review as I am already involved in other parts of the TF ecosystem.
Can you try to send a message to the TF Italian Group (Rome) at https://www.tensorflow.org/community/groups#europe ?

**Comment by bhack** [comment]
> I think the community strength is more in translating technical terms and providing feedback, so, in the future, I'd like to make it easier for the community to contribute to the glossary.

But generally I agree with this

**Comment by lamberta** [comment]
> Can you try to send a message to the TF Italian Group (Rome)

I am not a member of this Meetup group, but happy to message the organizer if you have a contact.

@mcaci If you are willing to maintain a community fork on your GitHub account, I can add a link from this repo.

**Review by lamberta — APPROVED** [review]
Let's merge. But will be difficult to keep this community project going without official support

**Comment by bhack** [comment]
@lamberta I agree with you but do you see also how many PR I have on hold on TF by months? I am a bit discouraged to open new PR in Tensorflow itself until my queue will start to be empty :wink:

**Pull request merged**
