### PR TITLE
zh-cn: fixing zh-cn/tutorials/distribute/keras.ipynb using nb_code_sync

### PR DESCRIPTION
**Pull request by logiccodes**
The notebook is updated using [nb_code_sync.py](https://github.com/tensorflow/docs-l10n/blob/master/tools/translation/nb_code_sync.py) tools.

```shell
docs-l10n $ python tools/translation/nb_code_sync.py site/zh-cn/tutorials/distribute/keras.ipynb --site_root tensorflow_docs_path/site/en --src tensorflow_docs_path/docs/site/en/tutorials/distribute/keras.ipynb
```

I don't know whether this is the right way to fix this problem.

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks. Looks like it worked. Can you also run these notebooks through the [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) tool to help make the diff more readable?

**Comment by Mr-Linus** [comment]
I tried it & it worked.
```shell
Notebook: keras.ipynb
  Missing TF2 Version: (%tensorflow_version 2.x|tensorflow.compat.v2)
  Found warnings. Notebook not written, skipping.
```
It looks like the format tools needs absl-py.
I think it will be better if the format tools set in CI ?
@lamberta

**Comment by lamberta** [comment]
Yes, requires absl and eventually plan to add to CI. But still testing it.

Since this notebook uses `tf-nightly` now, you can run `nbfmt.py --ignore_warn ...`

**Comment by logiccodes** [comment]
The notebook is formatted using `nbfmt.py --ignore_warn ...`. I have noticed that the order of items are changed.

**Comment by lamberta** [comment]
Thanks, appreciate it. Yes, `nbfmt` alpha sorts JSON fields and sets the indentation. This should make the diffs easier to read in GitHub (which has poor support for notebooks).
Looks like the notebook renders correctly. Thanks for testing :)

**Comment by logiccodes** [comment]
Got it, thanks for your explanation. :)

**Pull request merged**
