### PR TITLE
[MRG] Add Arabic translation of tutorials/quickstart/advanced notebook

### PR DESCRIPTION
**Pull request by mohamed-ali**
Adds arabic translation of tutorials/quickstart/advanced notebook

### CODE REVIEW

**Comment by mohamed-ali** [comment]
@lamberta  I adjusted this PR to follow the plan agreed upon in https://github.com/tensorflow/docs-l10n/issues/129. I also run nbfmt.py on the notebook. 

@tayciryahmed @baheytharwat could you review? 

Thanks.

**Comment by mohamed-ali** [comment]
@lamberta Should the tutorial appear automatically on Tensorflow's website  https://www.tensorflow.org/tutorials/quickstart/advanced?hl=ar  or is it a separate pipeline that gets triggered later on?

**Comment by lamberta** [comment]
Once the pipeline is created and running, we update tensorflow.org from translations once a week (Friday iirc).

**Comment by mohamed-ali** [comment]
@lamberta Good to know. Thanks for clarifying.

**Pull request merged**
