### PR TITLE
zh-cn: fixing zh-cn/tutorials/images/segmentation.ipynb using nb_code_sync

### PR DESCRIPTION
**Pull request by logiccodes**
Using [nb_code_sync](https://github.com/tensorflow/docs/blob/master/tools/nb_code_sync.py) and [nbfmt](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) to sync and format the segmentation.ipynb.

### CODE REVIEW

**Comment by tigerneil** [comment]
The translation has no problem. However, there is a problem when I try the code. https://github.com/tensorflow/tensorflow/issues/31171

**Comment by logiccodes** [comment]
> The translation has no problem. However, there is a problem when I try the code. [tensorflow/tensorflow#31171](https://github.com/tensorflow/tensorflow/issues/31171)

Thanks for pointing out. There is a `wrong checksum` error when downloading the pets dataset using `tfds.load`. I've tried https://github.com/tensorflow/tensorflow/issues/31171#issuecomment-619580795 in `Colab` and it has solved the issue. The code is synced with the latest `tensorflow/docs` repository. I'm wondering whether this will be fixed in the official docs.

**Comment by lamberta** [comment]
Please send a pull request to the tensorflow/docs repo if you find an issue :)

**Comment by logiccodes** [comment]
> Please send a pull request to the tensorflow/docs repo if you find an issue :)

Got it, thanks! :) The pull request to the tensorflow/docs repo is https://github.com/tensorflow/docs/pull/1556

I'm not so sure whether this or a patch in tensorflow_dataset repo will be a better idea.

**Comment by tigerneil** [comment]
let us wait for the fix. @logiccodes

**Review by lamberta — APPROVED** [review]

**Comment by lamberta** [comment]
Thank you and sorry for the delay.

As mentioned on the [mailing list](https://groups.google.com/a/tensorflow.org/g/docs/c/G23C6ZxjiUI/m/z8G87HTfBQAJ), we're directing the community to work alongside vendors in our [GitLocalize project](https://gitlocalize.com/tensorflow/docs-l10n). It's the only way to make sure the translations are in sync with the updated source material. The community can submit pull requests through GitLocalize and provide reviews.

But this notebook isn't yet reflected in the GitLocalize UI so will merge. In the future please sumit PRs and reviews here: https://gitlocalize.com/repo/4592/zh-cn/site/en-snapshot/tutorials

Thank you

**Pull request merged**
