### PR TITLE
[it] tutorials-keras-text_classification_with_hub.ipynb Basic translation

### PR DESCRIPTION
**Pull request by codeadmin-peritiae**

### CODE REVIEW

**Comment by gmb-ftcont** [comment]
lgtm

**Comment by codeadmin-peritiae** [comment]
Goodmorning @lamberta, 
is there still some mistake into this translation?

**Comment by lamberta** [comment]
Thanks for following up

Looks like the lint CI is failing (can ignore the labeler, that's a known issue) ...

Can click the "Details" link and looks like the button URLs are incorrect.

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nblint --arg=repo:tensorflow/docs-1l0n \
    --styles=tensorflow,tensorflow_docs_l10n notebook.ipynb
```

**Comment by codeadmin-peritiae** [comment]
@lamberta
I fixed the link issues.
Please, have a look to other PR still open.
Thank you.
Gianluca

**Pull request merged**
