### PR TITLE
[JA] Update README.md and  CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by AseiSugiyama**
This PR contains following changes.

- Add `community` directory to do not translate
- Fix link to docs-l10n

### CODE REVIEW

**Comment by kiszk** [comment]
[Weak suggestion]
`Contributing.md` at line 9: `en` -> `en-snapshot`

**Comment by AseiSugiyama** [comment]
Thank you for your suggestion, I agree with you.

**Comment by kiszk** [comment]
Thank you, LGTM

**Comment by agrexgh** [comment]
Thank you for adding rules for Japanese contributor!

I found an small typo.
At "### Additional Do not translate",
"because it is a a contribution" is to be corrected to 
“ because it is a contribution".

**Comment by AseiSugiyama** [comment]
Thank you for reviewing, I fixed it.

**Comment by lamberta** [comment]
Thanks. FYI, the `en-snapshot` directory is being used to test GitLocalize integration (since they do not support multiple repos, at this time). In the future we'll remove this.

I'll have more details about GitLocalize in the future, but currently exploratory.

**Pull request merged**
