### PR TITLE
[ES] Translations (1/2)

### PR DESCRIPTION
**Pull request by ilyaspiridonov**
Translated by Alconost

### CODE REVIEW

**Comment by ilyaspiridonov** [comment]
Lint warnings are missing licence of copyright cells (inherited from EN source counterparts)

**Comment by ilyaspiridonov** [comment]
Lint warnings are copyright or license cells missing (inherited from English counterparts)

**Comment by ilyaspiridonov** [comment]
@pcoet Can this one be merged? As in Pt-BR, I have removed one file that was not parsed correctly on our end due to a random tag in the English counterpart, and appeared as not translated

**Review by pcoet — APPROVED** [review]
No concerns about the lint warnings. Sanity checks of docs look fine. LGTM.

**Pull request merged**
