### PR TITLE
Update documents.

### PR DESCRIPTION
**Pull request by seo-inyoung**
Hi
we updated three documents and translated them into Korean.
It was conducted with permission from Google Group [TensorFlow Korean translation contributors] first.

We referred to the following github document.
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification.ipynb
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/text.ipynb
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/images.ipynb

I hope our translated document will be helpful.
Thank you.

### CODE REVIEW

**Comment by jaketae** [comment]
Hi @seo-inyoung, thank you so much for the PR. I appreciate your contribution!

Sadly, however, it looks like the CI is complaining that the following notebooks haven't been formatted properly. 

```
- site/ko/tutorials/load_data/images.ipynb
- site/ko/tutorials/load_data/text.ipynb
```

Can you try formatting these notebooks using [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py)? To run the script, install the dependencies and run 

```
nbfmt.py [options] notebook.ipynb [...]
```

Let me know if you have any questions!

**Comment by seo-inyoung** [comment]
@jaketae 
Where should I run that code?
I really want to solve it and contribute.

**Comment by jaketae** [comment]
There's no one right way to do it, but I typically run it in the command line. Here's one way that I think would be the easiest for you. 

1. [Download](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) the script and place it in some directory (it's easier if you place it in the same directory as your notebooks).
2. `cd` into that directory from your terminal. 
3. Assuming you've placed nbfmt.py in the same directory where the notebooks are located,  run

```
python nbfmt.py {notebook_title}.ipynb
```

4. After the notebooks have been formatted, push the files again. Just make sure that you don't accidentally push nbfmt.py along with your notebooks, if you decide to place them in the same directory. 

Please feel free to ask more questions, should there be any!

-------------

Hello @rickiepark, do you think it would help to edit README.md and add details on how to run nbfmt.py and nb_code_sync.py for new contributors?

**Comment by seo-inyoung** [comment]
@jaketae  I'm done!! Should I send the script again?!

**Comment by jaketae** [comment]
Yes, you have to commit and push the changes to the same branch. If you type something like `git status` or `git diff {notebook_title}.ipynb`, you should be able to see that edits were made to the notebooks. Stage and commit them to update this PR. (Don't add nbfmt.py though---just add the notebooks.)

So yes, please push the notebooks again! Thank you so much.

**Pull request closed without merging**
