### PR TITLE
[MRG][ar] Add README.md for Arabic translations

### PR DESCRIPTION
**Pull request by mohamed-ali**
This PR adds the README.md file to the Arabic translations.

### CODE REVIEW

**Comment by baheytharwat** [comment]
I checked 'Files changed', The format is not  shown properly. I think <div dir=“rtl”> </div> doesn't work well in Mark down files.

**Comment by tayciryahmed** [comment]
@baheytharwat It is actually rendered in the right way (right to left). You can see here : https://github.com/mohamed-ali/docs-l10n/tree/readme/site/ar 

It is only the diffs in the 'Files changed' tab that do not support rtl, it seems.

**Comment by tayciryahmed** [comment]
@lamberta Shouldn't the community translations disclaimer be translated too ?

**Comment by mohamed-ali** [comment]
@tayciryahmed  I looked at the README for French, Spanish, Italian and Japanese and saw that all of them have a translated version of the disclaimer alongside the English one, therefore, I did the same. 

@lamberta could you confirm that this is the recommended way? (english + translated disclaimer) 

Thanks.

**Comment by mohamed-ali** [comment]
@tayciryahmed @baheytharwat I added more guidelines on how to translate. Let me know if you have questions about them. 

As mentioned by @tayciryahmed the readme can be seen in this original repo from which this PR is created: https://github.com/mohamed-ali/docs-l10n/tree/readme/site/ar 

@lamberta @yashk2810 could review and merge when possible? Thanks.

**Pull request merged**
