### PR TITLE
[RU] added translations for site/ru/tutorials/images/

### PR DESCRIPTION
**Pull request by stahh**

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you. May take some time to review this many files at once.

Can someone from [REVIEWERS](https://github.com/tensorflow/docs-l10n/blob/master/site/ru/REVIEWERS) take a look, please?
cc: @0101011 @stabuev @nastikas @ilyaspiridonov @staskostenkov

And seems the bot is confused about the preview links. I'll look into it 🤖

**Comment by stabuev** [comment]
@lamberta, I don't have enough time to do a detailed review, but I looked through the files and thought that they could be merged. So LGTM. 

By the way, I tried to translate a notebook with gitlocalize but stop to do it as it is very inconvenient as it was in WYSIWYG mode.

**Comment by lamberta** [comment]
Thank you @stabuev for the review! Yes, I'm fine if we don't have a detailed review, but just want to make sure it meets a minimum threshold that does not harm, no spam, etc.

> By the way, I tried to translate a notebook with gitlocalize but stop to do it as it is very inconvenient as it was in WYSIWYG mode.

You can continue to work with notebooks and send PRs directly to GitHub, that's fine (GitLocalize will sync). But some folks, especially vendors, are unable to work directly with notebooks. Both workflows create pull requests.

**Review by lamberta — APPROVED** [review]
Thanks for the translation! 🚀

**Comment by stahh** [comment]
> Thank you @stabuev for the review! Yes, I'm fine if we don't have a detailed review, but just want to make sure it meets a minimum threshold that does not harm, no spam, etc.
> 
> > By the way, I tried to translate a notebook with gitlocalize but stop to do it as it is very inconvenient as it was in WYSIWYG mode.
> 
> You can continue to work with notebooks and send PRs directly to GitHub, that's fine (GitLocalize will sync). But some folks, especially vendors, are unable to work directly with notebooks. Both workflows create pull requests.

Don't worry, not spam, not harm =) I'm just learning tensorflow and decided to translate some tutorials in the learning process.

**Comment by lamberta** [comment]
Appreciate it—thank you!

**Pull request merged**
