### PR TITLE
[it] tutorials-keras-overfit_and_underfit.ipynb Reviewed translation

### PR DESCRIPTION
**Pull request by codeadmin-peritiae**

### CODE REVIEW

**Comment by codeadmin-peritiae** [comment]
@lamberta 

I checked Python3

I ran nbfmt without issues

% ./nbfmt.py ../../docs-l10n/site/it/tutorials/keras/overfit_and_underfit.ipynb
Notebook: ../../docs-l10n/site/it/tutorials/keras/overfit_and_underfit.ipynb
%

The notebook automatic checking still fails
Some suggestions?
Thank you.

**Comment by lamberta** [comment]
> I ran nbfmt without issues

Did you commit and push your nbfmt change?
Briefly looking at the diff: the `"metadata"` field appears before `"cells`" ---that shouldn't happen since nbfmt orders these alphabetically.

**Comment by codeadmin-peritiae** [comment]
> > I ran nbfmt without issues
> 
> Did you commit and push your nbfmt change?

I tried...
There was nothing to commit!
The files before and after the nbfmt running were identical...

> Briefly looking at the diff: the `"metadata"` field appears before `"cells`" ---that shouldn't happen since nbfmt orders these alphabetically.

Despite your It looks like nbfmt doesn't change the file...

I tried to compare the files before and after, and this is the result:
image

**Comment by lamberta** [comment]
Pulled your pr and ran nbfmt. It fixed the notebook and now passes the CI.
You can see the commit it added here: https://github.com/tensorflow/docs-l10n/pull/205/commits/9b5d022ac95593056111c1ae4bda5a4f26676d5d

Seems to work from the command-line. It it possible your editor is autoformatting?

**Comment by codeadmin-peritiae** [comment]
> Pulled your pr and ran nbfmt. It fixed the notebook and now passes the CI.
> You can see the commit I added here: [9b5d022](https://github.com/tensorflow/docs-l10n/commit/9b5d022ac95593056111c1ae4bda5a4f26676d5d)
> 
> Seems to work from the command-line. It it possible your editor is autoformatting?

**Solved.**
I ran an old version of nbfmt... 
I pulled the up-to-date version, I tried on a different pull request: "save_and_load", and it works well.

I'm going to format other blocked pull requests...

Thank you.

**Comment by gmb-ftcont** [comment]
lgtm

**Pull request merged**
