### PR TITLE
[KO] Update notebooks for Issue #184

### PR DESCRIPTION
**Pull request by rickiepark**
Fix for #184.

Files:
site/ko/tutorials/distribute/multi_worker_with_keras.ipynb
site/ko/tutorials/keras/save_and_load.ipynb
site/ko/swift/python_interoperability.ipynb
site/ko/guide/random_numbers.ipynb

* Correct some typos in translation.
* Update by nbfmt and nb_code_syn.
* Check with Colab.

Thanks

### CODE REVIEW

**Comment by rickiepark** [comment]
@googlebot I consent.

**Comment by jaketae** [comment]
@googlebot I consent.

**Comment by rickiepark** [comment]
I updated random_numbers.ipynb and multi_worker_with_keras.ipynb from latest en version.

Hi reviewers(@cre8tor, @Choiuijin1125, @JKIsaacLee, @NoelBird, @wckim, @eat-toast, @jaketae)
These notebooks are failed to publish, because en version has changed.
To continue publishing, could please to review this PR? :)

Thanks a lot!

**Comment by yashk2810** [comment]
I have approved it. Let's merge this.

**Comment by lamberta** [comment]
Thanks. Fixed a merge conflict when rebasing and used the changes in this branch.

**Pull request merged**
