### PR TITLE
zh_cn: updating /tutorials/estimator/boosted_trees_model_understanding.ipynb

### PR DESCRIPTION
**Pull request by Hedgeh09**
Update code of "visualize model fitting" part;
Modify description.

### CODE REVIEW

**Comment by Hedgeh09** [comment]
@duanw0916 @lamberta Please check the problem below.This translated file is not shown in the official website (https://tensorflow.google.cn/tutorials/estimator/boosted_trees_model_understanding).

**Comment by Hedgeh09** [comment]
@duanw0916 @lamberta Please check the problem below.

This translated file is not shown in the official website, it should be shoen on: https://tensorflow.google.cn/tutorials/estimator/boosted_trees_model_understanding

**Comment by lamberta** [comment]
Thanks, @Hedgeh09 . Since the outputs are saved this should have been published. Looking into it. cc: @yashk2810

**Comment by yashk2810** [comment]
Looks fixed now.

**Comment by lamberta** [comment]
Just published and can see it now: https://tensorflow.google.cn/tutorials/estimator/boosted_trees_model_understanding?hl=zh-cn
Thanks!

**Comment by Hedgeh09** [comment]
Hi @lamberta , @duanw0916 , @yashk2810 

Thank you for sovling the problem. That is your brilliant cooperation making our TF community getting more prosperous!

**Pull request merged**
