### PR TITLE
[RU] Fixed text for site/ru/guide

### PR DESCRIPTION
**Pull request by stahh**

### CODE REVIEW

**Comment by stahh** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
Thanks @stahh ,
We're encouraging contributors to use the GitLocalize project to submit translations: https://gitlocalize.com/repo/4592/ru/site/en-snapshot

Can someone from [REVIEWERS](https://github.com/tensorflow/docs-l10n/blob/master/site/ru/REVIEWERS) take a quick look, please?
cc: @0101011 @stabuev @nastikas @ilyaspiridonov @staskostenkov

**Comment by stabuev** [comment]
LGTM, valuable changes. Great work.

**Review by lamberta — APPROVED** [review]
Great! Thanks for the translation and review 🚀

**Pull request merged**
