### PR TITLE
[JA] Fix broken link of TensorBoard notebooks.

### PR DESCRIPTION
**Pull request by AseiSugiyama**
This PR fixes broken links in two notebooks.

- [Visualizing Data using the Embedding Projector in TensorBoard](https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin?hl=ja)
- [Hyperparameter Tuning with the HParams Dashboard](https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams?hl=ja)

Hyperlinks in these two notebooks are valid in English but broken in Japanese, so I fixed them.

### CODE REVIEW

**Comment by AseiSugiyama** [comment]
@lamberta I think we can merge this Pull Request safely without any translator's review because this Pull Request doesn't contain any changes about translated texts.

**Comment by AseiSugiyama** [comment]
@lamberta Sorry, but please DO NOT MERGE. GitHub Actions overwrote my fix and break the link again.

**Comment by AseiSugiyama** [comment]
Probably, I was able to solve the issue that the bot break the hyperlink.

I found three issues. The first is about this repo. The second one causes that CI breaks hyperlinks. It is related to both [tensorflow/docs](https://github.com/tensorflow/docs) and [tensorflow/tensorboard](https://github.com/tensorflow/tensorboard/tree/master/docs). The third one is about GitHub Actions.

The first one is only a typo. I fixed it in this PR https://github.com/tensorflow/docs-l10n/pull/499

Second, each notebook must have the "download notebook" button on the top of the notebook, however, notebooks of Tensorboard don't have the button. This condition is described in the `nbfmt` tool and checked in CI 

https://github.com/tensorflow/docs/blob/16082db0a6299f381978e1a183fa9f3ec65652a0/tools/tensorflow_docs/tools/nblint/style/tensorflow.py#L181[…]-L184 

Third, GitHub Action always applies both commands to changed files.

```console
$ python3 -m tensorflow_docs.tools.nbfmt <changed_notebook.ipynb>
$ python3 -m tensorflow_docs.tools.nblint --fix --verbose --arg=repo:tensorflow/docs-l10n  --styles=tensorflow,tensorflow_docs_l10n <changed_notebook.ipynb>
```

Even if the commands described in [the bot's interaction](https://github.com/tensorflow/docs-l10n/pull/498#issuecomment-808669230) are passed without any issues, after making a pull request, GitHub action might make a change the files included pull request.

In this repo, GitHub Action breaks hyperlinks by the command `python3 -m tensorflow_docs.tools.nblint --fix --verbose --arg=repo:tensorflow/docs-l10n  --styles=tensorflow,tensorflow_docs_l10n <changed_notebook.ipynb>`. To avoid this, we have to following conditions;

1. The table that has class "tfo-notebook-buttons" must have four buttons; "View on TensorFlow.org", "Run in Google Colab", "View source on GitHub", and "Download notebook"
2. For each td element, HTML tags must follow the ordering as `<td><a href=...>Button Name></a></td>`

**Comment by AseiSugiyama** [comment]
@lamberta I guess this PR is ready for merge. The same issue can happen in other languages including en, I will fix the docs in tensorflow/tensorboard.

**Review by lamberta — APPROVED** [review]
Thanks!
Yes, some en/ notebooks fail lint and this can be difficult to enforce across all the repos. Ideally we can fix this upstream but can merge a lint fail if there's a reason. It's mostly a warning.

**Pull request merged**
