### PR TITLE
zh-CN: translate tbdev_getting_started.ipynb

### PR DESCRIPTION
**Pull request by ccw1996**
translate https://github.com/tensorflow/tensorboard/blob/master/docs/tbdev_getting_started.ipynb

note: tbdev_getting_started.ipynb is already create pull request in https://github.com/tensorflow/docs-l10n/pull/13, and waiting for merge.

### CODE REVIEW

**Comment by lamberta** [comment]
CI is failing: Please run notebooks through [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py).

Looks like https://github.com/tensorflow/docs-l10n/pull/13 is ready (after nbfmt), so reviewers should *not* review the `get_started.ipynb` notebook in this PR

**Comment by lamberta** [comment]
`get_started.ipynb` has been merged: https://github.com/tensorflow/docs-l10n/pull/13
Please remove from this PR and resolve merge conflicts. Thanks

**Comment by ccw1996** [comment]
i close this pr and create a new one in 
https://github.com/tensorflow/docs-l10n/pull/162

 Wish you good health and happiness.

**Comment by ccw1996** [comment]
i close this pr and create a new one in
#162

Wish you good health and happiness.

**Pull request closed without merging**
